"use client";
import { useState, useEffect } from 'react';
import { FileText, CheckCircle, Clock, AlertCircle, User, RefreshCcw, Download } from 'lucide-react';
import { toast } from 'react-hot-toast';
import { jsPDF } from "jspdf";

export default function AdminRequests() {
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);

  const fetchReports = async () => {
    setLoading(true);
    const token = typeof window !== 'undefined' ? localStorage.getItem('token') : null; 
    
    if (!token) {
        setLoading(false);
        return;
    }

    try {
      const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/api/support/all`, {
        headers: { 'Authorization': `Bearer ${token}` }
      });
      
      const data = await res.json();

      if (res.ok && Array.isArray(data)) {
         setReports(data);
      } else {
         setReports([]);
      }
    } catch (error) {
      console.error(error);
      toast.error("Connection error");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchReports();
  }, []);

  // 2. 🔥 UPDATED PDF GENERATOR WITH LOGO
  const downloadPDF = (report) => {
    const doc = new jsPDF();

    // --- 1. LOGO: BrainBuffer ---
    // "Brain" -> Dark Slate (Almost Black)
    doc.setFontSize(26);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(15, 23, 42); // Slate-900
    doc.text("Brain", 20, 25);

    // "Buffer" -> Emerald Green
    const brainWidth = doc.getTextWidth("Brain");
    doc.setTextColor(16, 185, 129); // Emerald-500
    doc.text("Buffer", 20 + brainWidth, 25);

    // --- 2. SUBTITLE & STATUS ---
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(100, 116, 139); // Slate-500
    doc.text("OFFICIAL SUPPORT TICKET", 20, 32);

    // Status Badge (Top Right)
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    if (report.status === 'open') {
        doc.setTextColor(245, 158, 11); // Amber
        doc.text("STATUS: OPEN", 150, 25);
    } else {
        doc.setTextColor(16, 185, 129); // Green
        doc.text("STATUS: RESOLVED", 140, 25);
    }

    // --- 3. DECORATIVE LINE ---
    doc.setDrawColor(16, 185, 129); // Green Line
    doc.setLineWidth(1);
    doc.line(20, 38, 190, 38);

    // --- 4. CONTENT ---
    doc.setTextColor(0, 0, 0); // Reset to Black
    doc.setFontSize(12);
    doc.setFont("helvetica", "normal");
    
    let y = 60; // Start Y Position

    // Helper to print lines
    const addLine = (label, value) => {
        doc.setFont("helvetica", "bold");
        doc.setTextColor(71, 85, 105); // Label Color (Slate-600)
        doc.text(`${label}:`, 20, y);
        
        doc.setFont("helvetica", "normal");
        doc.setTextColor(0, 0, 0); // Value Color (Black)
        doc.text(value || "N/A", 60, y);
        y += 12;
    };

    addLine("Report ID", report._id);
    addLine("Date", new Date(report.created_at).toLocaleString());
    addLine("Category", report.type.toUpperCase());
    y += 5; 
    addLine("User ID", report.user_id);
    addLine("Match ID", report.match_id);

    y += 10;
    doc.setDrawColor(226, 232, 240); // Light Slate Line
    doc.line(20, y, 190, y); 
    y += 15;

    // -- DESCRIPTION BOX --
    doc.setFont("helvetica", "bold");
    doc.setTextColor(71, 85, 105);
    doc.text("Issue Description:", 20, y);
    y += 10;
    
    doc.setFont("helvetica", "normal");
    doc.setTextColor(30, 41, 59); // Dark text for description
    // Split text to fit page width
    const splitText = doc.splitTextToSize(report.description, 170);
    doc.text(splitText, 20, y);

    // -- FOOTER --
    doc.setFontSize(10);
    doc.setTextColor(150);
    doc.text("Generated by BrainBuffer Admin Panel", 20, 280);

    // Save File
    doc.save(`Support_Report_${report._id.substring(0,8)}.pdf`);
    toast.success("PDF Downloaded!");
  };

  return (
    <div className="p-4 md:p-6 max-w-7xl mx-auto">
      
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-8">
        <div>
          <h1 className="text-xl md:text-2xl font-black text-slate-900 uppercase tracking-tight">User Requests</h1>
          <p className="text-slate-500 text-sm font-medium">Manage support tickets and disputes</p>
        </div>
        <button onClick={fetchReports} className="self-start sm:self-auto p-3 bg-white border border-slate-200 rounded-xl hover:bg-slate-50 text-slate-500 transition-all shadow-sm active:scale-95">
          <RefreshCcw size={20} className={loading ? "animate-spin" : ""} />
        </button>
      </div>

      {/* Stats Cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4 md:gap-6 mb-8">
        <div className="bg-white p-6 rounded-3xl border border-slate-100 shadow-xl shadow-slate-200/50">
          <div className="flex items-center gap-4">
            <div className="p-3 bg-blue-50 text-blue-500 rounded-2xl"><FileText size={24}/></div>
            <div>
              <p className="text-xs font-bold text-slate-400 uppercase tracking-wider">Total Reports</p>
              <p className="text-3xl font-black text-slate-800">{reports?.length || 0}</p>
            </div>
          </div>
        </div>
        <div className="bg-white p-6 rounded-3xl border border-slate-100 shadow-xl shadow-slate-200/50">
          <div className="flex items-center gap-4">
            <div className="p-3 bg-amber-50 text-amber-500 rounded-2xl"><Clock size={24}/></div>
            <div>
              <p className="text-xs font-bold text-slate-400 uppercase tracking-wider">Pending</p>
              <p className="text-3xl font-black text-slate-800">
                {reports?.filter(r => r.status === 'open').length || 0}
              </p>
            </div>
          </div>
        </div>
        <div className="bg-white p-6 rounded-3xl border border-slate-100 shadow-xl shadow-slate-200/50">
          <div className="flex items-center gap-4">
            <div className="p-3 bg-emerald-50 text-emerald-500 rounded-2xl"><CheckCircle size={24}/></div>
            <div>
              <p className="text-xs font-bold text-slate-400 uppercase tracking-wider">Resolved</p>
              <p className="text-3xl font-black text-slate-800">
                {reports?.filter(r => r.status === 'resolved').length || 0}
              </p>
            </div>
          </div>
        </div>
      </div>

      {/* Table */}
      <div className="bg-white border border-slate-100 rounded-[2rem] shadow-xl shadow-slate-200/40 overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse min-w-[800px] md:min-w-full">
            <thead>
              <tr className="bg-slate-50/50 border-b border-slate-100">
                <th className="p-4 md:p-6 text-[10px] font-black text-slate-400 uppercase tracking-widest">Action</th>
                <th className="p-4 md:p-6 text-[10px] font-black text-slate-400 uppercase tracking-widest">Type</th>
                <th className="p-4 md:p-6 text-[10px] font-black text-slate-400 uppercase tracking-widest">User / Match</th>
                <th className="p-4 md:p-6 text-[10px] font-black text-slate-400 uppercase tracking-widest w-1/3">Description</th>
                <th className="p-4 md:p-6 text-[10px] font-black text-slate-400 uppercase tracking-widest text-right">Date</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-50">
              {loading ? (
                <tr>
                  <td colSpan="5" className="p-10 text-center text-slate-400 font-bold animate-pulse">Loading requests...</td>
                </tr>
              ) : !reports || reports.length === 0 ? (
                <tr>
                  <td colSpan="5" className="p-10 text-center text-slate-400 font-bold">No requests found.</td>
                </tr>
              ) : (
                reports.map((report) => (
                  <tr key={report._id} className="hover:bg-slate-50/50 transition-colors group">
                    <td className="p-4 md:p-6">
                      <button 
                        onClick={() => downloadPDF(report)}
                        className={`inline-flex items-center gap-2 px-3 py-2 rounded-lg text-[10px] font-black uppercase tracking-wide border transition-all active:scale-95 ${
                          report.status === 'open' 
                            ? 'bg-amber-50 text-amber-600 border-amber-100 hover:bg-amber-100' 
                            : 'bg-emerald-50 text-emerald-600 border-emerald-100 hover:bg-emerald-100'
                        }`}
                        title="Download Report PDF"
                      >
                        <Download size={14} />
                        {report.status}
                      </button>
                    </td>
                    <td className="p-4 md:p-6">
                      <span className="font-bold text-slate-700 text-sm capitalize">{report.type}</span>
                    </td>
                    <td className="p-4 md:p-6">
                      <div className="flex flex-col gap-1">
                        <div className="flex items-center gap-2 text-xs font-bold text-slate-600">
                          <User size={12} className="text-slate-400"/> {report.user_id?.substring(0,8)}...
                        </div>
                        {report.match_id && (
                          <span className="text-[10px] font-mono text-slate-400 bg-slate-100 px-1.5 py-0.5 rounded w-fit">
                             Match: {report.match_id}
                          </span>
                        )}
                      </div>
                    </td>
                    <td className="p-4 md:p-6">
                      <p className="text-sm text-slate-600 font-medium leading-relaxed min-w-[200px]">{report.description}</p>
                    </td>
                    <td className="p-4 md:p-6 text-right">
                       <span className="text-xs font-bold text-slate-400 whitespace-nowrap">
                         {new Date(report.created_at).toLocaleDateString()}
                       </span>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}